Add `keywords` optional argument to `lookup_compound`
sAInaptic/symspellpy pull request #2
Opened 2023-10-05 13:18 UTC by TMoraru98

2023-10-05 14:07 UTC, Tiepies requested changes
Code duplication means refactoring, and I have doubts about the location where you added the keywords logic.

2023-10-05 14:07 UTC, Tiepies commented on symspellpy/symspellpy.py
> +                                                for k in keywords))):
1. Code duplication (that's what I meant by "refactor"). By extracting the duplicated code under an aptly named function or static method, the name of the function will also help in explaining what the code does (I don't really get it, though that's also because the context in which you added the new code is so opaque).
2. Why does this only apply if `verbosity == Verbosity.TOP`? In fact, why is this logic nested so deeply? I think the keywords logic should be somewhere around 615, i.e. outside the while loop. I might be misunderstanding the `lookup` method, but the keywords logic should not be interact with the values of other irrelevant parameters, like Verbosity.
3. `keywords` should probably be a single string, like spellcorrector_exceptions, not a list. That offers you more flexibility and should hopefully be more efficient (in particular, there's no point in creating a pipe-delimited regex, to then split it to match each component separately.

2023-10-05 14:35 UTC, TMoraru98 commented on symspellpy/symspellpy.py
> +                                                for k in keywords))):
Unfortunately, that is not how this dog forsaken function works. Verbosity is not at all irrelevant here since it tighly controls the space being searched by the marker. We use `Verbosity.TOP` in every case at the moment, and it is here where the top best term is picked. By line 615, with Verbosity set to TOP (as it is in all cases with us) the suggestions list contains only one element. It's only with `Verbosity.ALL` that `suggestions` has more than one element in it, and those will be all the suggestions within the set maximum distance. We could potentially use that but it presents a bunch of other messiness and is only useful for the version of this implementation where we always pick terms found in our keywords, but ofc you have to decide which one to pick under what circumstance. For example, with `Verbosity.ALL` "preditors" will have `['creditors', 'predators', 'predictors', 'editors', 'predator', 'creditor', 'predictor', 'predatory']` as candidates, and so we have to figure out what to do to get to "predators" and that logic will basically look smilar to what `Verbosity.TOP` is doing anyway.

Having said all that, I can see how Verbosity.CLOSEST might need this too.

2023-10-05 14:51 UTC, Tiepies commented on symspellpy/symspellpy.py
> +                                                for k in keywords))):
So, as mentioned in the chat, the point here is that you don't want the question whether keywords are used or not to be dependent on the value of `verbosity`. That's what I meant with verbosity being "irrelevant".

2023-10-05 16:06 UTC, TMoraru98 commented on symspellpy/symspellpy.py
> +                suggestions = self._pick_keywords(keywords, suggestions)
both ALL and CLOSEST will return more than one suggestion, so this bit tackels both.

2023-10-06 09:00 UTC, Tiepies requested changes
Just add some comment explaining the additional criterion on lines 595--600.

2023-10-06 10:22 UTC, Tiepies approved these changes
Nice work!

2023-10-06 10:23 UTC, merged